### ISSUE TITLE
create `style guide` page for new button styles, forms and heading styles

### ISSUE THREAD

**Issue by laurencebradford** [laurencebradford/jaacf#2]

**Comment by rxsharp** [comment]
Is this a good example? http://rxsharp.github.io/one-page-starter/main-template/elements.html

**Comment by rxsharp** [comment]
On my local environment, I added https://codex.wordpress.org/Theme_Unit_Test test data in xml. They give you instructions on how to install it with the WordPress installer plugin: https://wordpress.org/plugins/wordpress-importer/

**Comment by ciampam9** [comment]
@rxsharp , I branched out last night and started to build it out.  It will just make it easier for me to design the buttons etc.  Usually I just do it outright but since there are collaborators I want to make sure everyone is using the components properly.  I hope this makes sense...

**Comment by ciampam9** [comment]
@rxsharp lets wait on the unit test stuff.
